S_ADDON_VERSION = {
	-- |@Version: 1@|
	-- {build, "url", {"folder1", "folder2"}}
	{5, "AdvancedWotLKCombatLog", {"AdvancedWotLKCombatLog"}},
	{3, "AdvancedWotLKCombatLog_Helper", {"AdvancedWotLKCombatLog_Helper"}},
	{4, "ATT", {"ATT"}},
	{7, "Auctionator", {"Auctionator"}},
	{1, "BadBoy", {"BadBoy"}},
	{1, "BadBoy_CCleaner", {"BadBoy_CCleaner"}},
	{4, "Bagnon", {"Bagnon", "Bagnon_Config", "Bagnon_Forever", "Bagnon_GuildBank", "Bagnon_Tooltips"}},
	{1, "BankStack", {"BankStack"}},
	{4, "Bartender4", {"Bartender4"}},
	{4, "BigAuras", {"BigAuras"}},
	{1, "Capping", {"Capping"}},
	{2, "ChatBar", {"ChatBar"}},
	{5, "Clique", {"Clique"}},
	{3, "CustomEnhancedRaidFrames", {"CustomEnhancedRaidFrames"}},
	{3, "DiminishingReturns-Sirus", {"DiminishingReturns", "DiminishingReturns_Config"}},
	{3, "DrDamage", {"DrDamage"}},
	{2, "FishingBuddy", {"FishingBuddy"}},
	{1, "GnomishVendorShrinker", {"GnomishVendorShrinker"}},
	{3, "HealBot", {"HealBot", "TitanHealBot"}},
	{2, "MikScrollingBattleText", {"MikScrollingBattleText", "MSBTOptions"}},
	{11, "MoveAnything", {"MoveAnything"}},
	{2, "Omen", {"Omen"}},
	{1, "OmniCC", {"OmniCC", "OmniCC_Config"}},
	{1, "Postal", {"Postal"}},
	{1, "Quartz", {"Quartz"}},
	{2, "RaidRoll", {"RaidRoll", "RaidRoll_EPGP", "RaidRoll_LootTracker"}},
	{1, "Recount", {"Recount"}},
	{2, "RecountGuessedAbsorbs", {"RecountGuessedAbsorbs"}},
	{1, "RecountHealAndGuessedAbsorbs", {"RecountHealAndGuessedAbsorbs"}},
	{3, "sArena", {"sArena"}},
	{1, "SellJunk", {"SellJunk"}},
	{2, "TipTac", {"TipTac", "TipTacItemRef", "TipTacOptions", "TipTacTalents"}},
}